### ISSUE TITLE
Face does not return to Neutral Pose when microphone capture is not used

### ISSUE THREAD

**Issue by MNieves-LBI** [viniciushelder/OVRLipSync-UE5#1]
[In UOVRLipSyncActorComponent::Stop()](https://github.com/viniciushelder/OVRLipSync-UE5/blob/0b45893fd999a4485c9ef2267234f8b8f64ddaca/OVRLipSync/Source/OVRLipSync/Private/OVRLipSyncLiveActorComponent.cpp#L165)

InitNeutralPose() was moved behind the VoiceCapture Check.  If using OVR without Voice Capture, this causes faces to be frozen in the last Viseme.  Moving it back to before the check (Line 155) fixes this issue.

**Comment by viniciushelder** [comment]
Hi! Thanks for pointing it out.

> **was moved** behind the VoiceCapture Check.

I've checked the [latest ](https://developer.oculus.com/downloads/package/oculus-lipsync-unreal/)"official" plugin by Meta and InitNeutralPose() it's already after the check. Not sure if i've moved that.

I've done some testing with the function running before the VoiceCapture check but wasn't able to reproduce the issue, the viseme values always default to 0 (except the "sil", which is fine) when i call Stop() while using an cooked audio sequence.

Can you give me an step by step on how to reproduce the issue?

**Comment by MNieves-LBI** [comment]
I took another look at the various repositories and you are correct, you did not move it.  So this might be better understood as a feature request rather than a bug.

I do not currently use Voice Capture, instead relying on an audio buffer.  So when Stop is called InitNeutralPose() is not run.  Moving InitNeutralPose from where it is to Line 155 correctly resets the Neutral pose.  Alternatively, leaving InitNeutralPose where it is, and placing the VoiceCapture specific code inside the VoiceCapture guard a would also work

```
void UOVRLipSyncActorComponent::Stop()
{
	if (VoiceCapture != nullptr)
	{
		auto &TimerManager = GetWorld()->GetTimerManager();
		TimerManager.ClearTimer(VoiceCaptureTimer);
		VoiceCapture->Stop();
		VoiceCapture = nullptr;
	}

	InitNeutralPose();
}
```

**Comment by viniciushelder** [comment]
Done!

https://github.com/viniciushelder/OVRLipSync-UE5/releases/tag/5.3_v1.0.1
